### ISSUE TITLE
MAIN ENVIRONMENT: Set up main player room office environment

### ISSUE THREAD

**Issue by jamiepoli** [CodeTheChangeUBC/foundry10#6]
-Set up simple office environment using unity. Simple assets needed, ensure that everyone has access to them to ensure team-wide editing

*POINTERS*
-perspective is journalist-based, basis of room is simple environment with simple interaction points (i.e: a desk, billboard) relevant for a journalist

-Refer to google doc for further reference based on lore of the game.

-Place player here as their initial position.

**Comment by stolet** [comment]
I have uploaded the files for the main player office to onedrive.
